/*
 * This file was generated by qdbusxml2cpp version 0.8
 * Command line was: qdbusxml2cpp -m -a lattedockadaptor -i lattecorona.h -l Latte::Corona /home/kylin/ukui/ukui-dock/latte-dock-0.9.11/app/dbus/org.kde.LatteDock.xml
 *
 * qdbusxml2cpp is Copyright (C) 2020 The Qt Company Ltd.
 *
 * This is an auto-generated file.
 * This file may have been hand-edited. Look for HAND-EDIT comments
 * before re-generating it.
 */

#ifndef LATTEDOCKADAPTOR_H
#define LATTEDOCKADAPTOR_H

#include <QtCore/QObject>
#include <QtDBus/QtDBus>
#include "lattecorona.h"
QT_BEGIN_NAMESPACE
class QByteArray;
template<class T> class QList;
template<class Key, class Value> class QMap;
class QString;
class QStringList;
class QVariant;
QT_END_NAMESPACE

/*
 * Adaptor class for interface org.kde.LatteDock
 */
class LatteDockAdaptor: public QDBusAbstractAdaptor
{
    Q_OBJECT
    Q_CLASSINFO("D-Bus Interface", "org.kde.LatteDock")
    Q_CLASSINFO("D-Bus Introspection", ""
"  <interface name=\"org.kde.LatteDock\">\n"
"    <method name=\"activateLauncherMenu\"/>\n"
"    <method name=\"updateDockItemBadge\">\n"
"      <arg direction=\"in\" type=\"s\" name=\"identifier\"/>\n"
"      <arg direction=\"in\" type=\"s\" name=\"value\"/>\n"
"    </method>\n"
"    <method name=\"windowColorScheme\">\n"
"      <arg direction=\"in\" type=\"s\" name=\"windowIdAndScheme\"/>\n"
"    </method>\n"
"    <method name=\"switchToLayout\">\n"
"      <arg direction=\"in\" type=\"s\" name=\"layout\"/>\n"
"    </method>\n"
"    <method name=\"showSettingsWindow\">\n"
"      <arg direction=\"in\" type=\"i\" name=\"page\"/>\n"
"    </method>\n"
"    <method name=\"setContextMenuView\">\n"
"      <arg direction=\"in\" type=\"i\" name=\"id\"/>\n"
"    </method>\n"
"    <method name=\"contextMenuData\">\n"
"      <arg direction=\"out\" type=\"as\" name=\"data\"/>\n"
"    </method>\n"
"    <method name=\"setBackgroundFromBroadcast\">\n"
"      <arg direction=\"in\" type=\"s\" name=\"activity\"/>\n"
"      <arg direction=\"in\" type=\"s\" name=\"screenName\"/>\n"
"      <arg direction=\"in\" type=\"s\" name=\"filename\"/>\n"
"    </method>\n"
"    <method name=\"setBroadcastedBackgroundsEnabled\">\n"
"      <arg direction=\"in\" type=\"s\" name=\"activity\"/>\n"
"      <arg direction=\"in\" type=\"s\" name=\"screenName\"/>\n"
"      <arg direction=\"in\" type=\"b\" name=\"enabled\"/>\n"
"    </method>\n"
"  </interface>\n"
        "")
public:
    LatteDockAdaptor(Latte::Corona *parent);
    virtual ~LatteDockAdaptor();

    inline Latte::Corona *parent() const
    { return static_cast<Latte::Corona *>(QObject::parent()); }

public: // PROPERTIES
public Q_SLOTS: // METHODS
    void activateLauncherMenu();
    QStringList contextMenuData();
    void setBackgroundFromBroadcast(const QString &activity, const QString &screenName, const QString &filename);
    void setBroadcastedBackgroundsEnabled(const QString &activity, const QString &screenName, bool enabled);
    void setContextMenuView(int id);
    void showSettingsWindow(int page);
    void switchToLayout(const QString &layout);
    void updateDockItemBadge(const QString &identifier, const QString &value);
    void windowColorScheme(const QString &windowIdAndScheme);
Q_SIGNALS: // SIGNALS
};

#endif
